deploy:
  stage: deploy
  image: microsoft/azure-cli
  script:
    - az storage blob delete-batch -s "\$web" --connection-string $AZURE_STORAGE_CONNECTION_STRING
    - az storage blob upload -c "\$web" -f index.html -n index.html --connection-string $AZURE_STORAGE_CONNECTION_STRING
  only:
    - master